# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UniversalFormat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UniversalFormat.proto',
  package='syslab.universalcache',
  syntax='proto3',
  serialized_pb=_b('\n\x15UniversalFormat.proto\x12\x15syslab.universalcache\"\x98\x02\n\x04\x44\x61ta\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x33\n\x04meta\x18\x04 \x03(\x0b\x32%.syslab.universalcache.Data.MetaEntry\x12\x10\n\x06\x64ouble\x18\x64 \x01(\x01H\x00\x12\x0f\n\x05\x66loat\x18\x65 \x01(\x02H\x00\x12\r\n\x03int\x18\x66 \x01(\x05H\x00\x12\x0e\n\x04long\x18g \x01(\x03H\x00\x12\x0e\n\x04\x62ool\x18h \x01(\x08H\x00\x12\x10\n\x06string\x18i \x01(\tH\x00\x12\x0f\n\x05\x62ytes\x18j \x01(\x0cH\x00\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x07\n\x05valueB6\n!dk.syslab.protobuf.universalcacheB\x0fUniversalFormatH\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DATA_METAENTRY = _descriptor.Descriptor(
  name='MetaEntry',
  full_name='syslab.universalcache.Data.MetaEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='syslab.universalcache.Data.MetaEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='syslab.universalcache.Data.MetaEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=320,
)

_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='syslab.universalcache.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='syslab.universalcache.Data.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='syslab.universalcache.Data.channel', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='syslab.universalcache.Data.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='syslab.universalcache.Data.meta', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double', full_name='syslab.universalcache.Data.double', index=4,
      number=100, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float', full_name='syslab.universalcache.Data.float', index=5,
      number=101, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int', full_name='syslab.universalcache.Data.int', index=6,
      number=102, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='long', full_name='syslab.universalcache.Data.long', index=7,
      number=103, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bool', full_name='syslab.universalcache.Data.bool', index=8,
      number=104, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='string', full_name='syslab.universalcache.Data.string', index=9,
      number=105, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='syslab.universalcache.Data.bytes', index=10,
      number=106, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATA_METAENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='syslab.universalcache.Data.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=49,
  serialized_end=329,
)

_DATA_METAENTRY.containing_type = _DATA
_DATA.fields_by_name['meta'].message_type = _DATA_METAENTRY
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['double'])
_DATA.fields_by_name['double'].containing_oneof = _DATA.oneofs_by_name['value']
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['float'])
_DATA.fields_by_name['float'].containing_oneof = _DATA.oneofs_by_name['value']
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['int'])
_DATA.fields_by_name['int'].containing_oneof = _DATA.oneofs_by_name['value']
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['long'])
_DATA.fields_by_name['long'].containing_oneof = _DATA.oneofs_by_name['value']
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['bool'])
_DATA.fields_by_name['bool'].containing_oneof = _DATA.oneofs_by_name['value']
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['string'])
_DATA.fields_by_name['string'].containing_oneof = _DATA.oneofs_by_name['value']
_DATA.oneofs_by_name['value'].fields.append(
  _DATA.fields_by_name['bytes'])
_DATA.fields_by_name['bytes'].containing_oneof = _DATA.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['Data'] = _DATA

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(

  MetaEntry = _reflection.GeneratedProtocolMessageType('MetaEntry', (_message.Message,), dict(
    DESCRIPTOR = _DATA_METAENTRY,
    __module__ = 'UniversalFormat_pb2'
    # @@protoc_insertion_point(class_scope:syslab.universalcache.Data.MetaEntry)
    ))
  ,
  DESCRIPTOR = _DATA,
  __module__ = 'UniversalFormat_pb2'
  # @@protoc_insertion_point(class_scope:syslab.universalcache.Data)
  ))
_sym_db.RegisterMessage(Data)
_sym_db.RegisterMessage(Data.MetaEntry)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!dk.syslab.protobuf.universalcacheB\017UniversalFormatH\001'))
_DATA_METAENTRY.has_options = True
_DATA_METAENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
